### PR TITLE
Update reference to headers in the response.

### PR DESCRIPTION
**Pull request by litghost**
Proposed fix for #126

### CODE REVIEW

**Review by thatsed — CHANGES_REQUESTED** [review]
Hi, I came across the issue updating to Django 3.2. It is related (see [this comment](https://github.com/TracyWebTech/django-revproxy/issues/126#issuecomment-819903760) on the issue) to an upgrade to the HttpResponse headers interface, so changing the logging entries might get rid of the surface problem but won't actually update the library to full 3.2 compatibility. I left some notes in the review, and I'm making my own fork to further investigate the issue. I'll keep you updated!

**Comment by thatsed** [comment]
Also, these changes would make the library incompatible with previous versions of Django (<3.2), so some checks should be in place for that (that is why tests are failing after all).

My proposal is a check for the `headers` attribute on the response object: if missing, use old strategy; otherwise, use the 3.2 compatible one. A check on the Django version or the `django.http.response.ResponseHeaders` interface existence (by `try import`) are also viable options.

**Comment by timtan** [comment]
still meets the problem.  thanks for the PR and look forward to it

**Comment by leandrodesouzadev** [comment]
Is there any updates on this issue/pr?
I'm facing the same issue on Django 4.

**Comment by sumit4613** [comment]
This issue is already fixed and merged via #137. Closing this MR.

**Pull request closed without merging**
